const SET_ALERT = "SET_ALERT";
const REMOVE_ALERT = "REMOVE_ALERT";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAIL = "REGISTER_FAIL";
const USER_LOADED = "USER_LOADED";
const AUTH_FAIL = "AUTH_FAIL";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";
const LOG_OUT = "LOG_OUT";
const GET_PROFILE = "GET_PROFILE";
const ALL_PROFILES = "ALL_PROFILES";
const PROFILE_ERROR = "PROFILE_ERROR";
const CLEAR_PROFILE = "CLEAR_PROFILE";
const CREATE_PROFILE = "CREATE_PROFILE";
const EDIT_PROFILE = "EDIT_PROFILE";
const ADD_EXPERIENCE = "ADD_EXPERIENCE";
const ADD_EDUCATION = "ADD_EDUCATION";
const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";
const DELETE_EDUCATIOIN = "DELETE_EDUCATION";
const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export {
    SET_ALERT,
    REMOVE_ALERT,
    REGISTER_SUCCESS,
    REGISTER_FAIL,
    USER_LOADED,
    AUTH_FAIL,
    LOGIN_SUCCESS,
    LOGIN_FAIL,
    LOG_OUT,
    GET_PROFILE,
    PROFILE_ERROR,
    CLEAR_PROFILE,
    CREATE_PROFILE,
    EDIT_PROFILE,
    ADD_EDUCATION,
    ADD_EXPERIENCE,
    DELETE_EDUCATIOIN,
    DELETE_EXPERIENCE,
    DELETE_ACCOUNT,
    ALL_PROFILES,
};
